//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Till {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlImage serviceImg;
		
		protected System.Web.UI.WebControls.Label ServiceType;
		
		protected System.Web.UI.WebControls.Label ttlLbl;
		
		protected System.Web.UI.WebControls.Label ttlCost;
		
		protected System.Web.UI.WebControls.Button EatIn;
		
		protected System.Web.UI.WebControls.Button Takeaway;
		
		protected System.Web.UI.WebControls.Button Checkout;
		
		protected System.Web.UI.WebControls.GridView purchasedFoodView;
		
		protected System.Web.UI.WebControls.Label lblPrice;
		
		protected System.Web.UI.WebControls.Label lblAmount;
		
		protected System.Web.UI.WebControls.Button AddButton;
		
		protected System.Web.UI.WebControls.Button RemoveButton;
		
		protected System.Web.UI.WebControls.Button Info;
		
		protected System.Web.UI.WebControls.DropDownList BentoList;
		
		protected System.Web.UI.WebControls.Button Bento;
		
		protected System.Web.UI.WebControls.DropDownList SushiList;
		
		protected System.Web.UI.WebControls.Button Sushi;
		
		protected System.Web.UI.WebControls.DropDownList DrinkList;
		
		protected System.Web.UI.WebControls.Button Drink;
	}
}
