//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Till {
	
	
	public partial class Info {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label itemLbl;
		
		protected System.Web.UI.WebControls.Label itemName;
		
		protected System.Web.UI.WebControls.Label ingdLbl;
		
		protected System.Web.UI.WebControls.Label ingredients;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl descInfo;
		
		protected System.Web.UI.HtmlControls.HtmlImage itmImage;
		
		protected System.Web.UI.WebControls.Button bckHome;
	}
}
